package com.renz.EvenFibonacciNumbers;
/*
 * 

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


 */
public class EvenFibonacciNumbers {
	
	public static void main(String[] args){
		int max = 4000000;
		int total = 0;
		int pre = 0 ,holdnum = 0, num = 1 ;
		
		while (total < max){
			if (num % 2 == 0){
				total += num;
			}
			if (num <= 1){
				pre = num;
				num += 1;
			}
			else{
				holdnum = num;
				num += pre;
				pre = holdnum;
			}
			
			System.out.println(num + " + " + pre);
		}
		System.out.println("total : " + total);
	}
}
